### ISSUE TITLE
Blur Radius always resets to 8 when re-opening client with this mod, no matter what other value you set it to.

### ISSUE THREAD

**Issue by CalXee** [Motschen/Blur#6] opened 2020-12-13 03:11 UTC
No matter what value you have set, upon re-opening the client the blur radius is always the default 8. Even if the modmenu UI shows it's not 8, it is.

**Comment by Motschen** [comment] 2021-01-18 12:31
Cannot reproduce on my end, could you provide more information? Which minecraft version are you using? Are you using any other mods?

**Comment by CalXee** [comment] 2021-01-21 19:57
https://youtu.be/rpDfwvzSfTs is the video showcasing the issue. No other mods installed.

**Comment by YoshiAye** [comment] 2021-02-15 23:17
Same issue here. Version is 1.16.5

**Comment by Motschen** [comment] 2021-03-05 17:56
Could you try if it also happens on 2.1.0?

**Comment by Justsnoopy30** [comment] 2021-03-07 17:30
It does, just confirmed.

**Comment by Justsnoopy30** [comment] 2021-03-07 17:33
Well actually it happens 100% of the time when blur radius is set to 0, and sometimes when it is set to 1 or above.

**Comment by Motschen** [comment] 2021-09-24 16:52
Doesn't seem to occur in the latest version anymore, can you confirm?

**Comment by Motschen** [comment] 2022-10-19 18:23
Gonna close this now, since it seems to be fixed.

**Closed as completed by Motschen** 2022-10-19 18:23 UTC
Labels: maybe-fixed
