### ISSUE TITLE
Chat not bluring with Optifabric

### ISSUE THREAD

**Issue by imasheep1** [Motschen/Blur#17] opened 2021-06-27 08:21 UTC
So I use OptiFabric. I like Optifine and Forge isn't currently out
When I open the game without optifine or optifabric in my mod folder, the default config will work as expected, and the chat will not blur the screen

However, when I use Optifabric and Optifine, opening the chat will still blur the screen. Is there a way I can fix this or is this a problem with one of these mods?

Using the latest version of Blur, Optifabric 1.11.9, and Optifine 1.17 HD U G9 pre23

**Comment by tort-oise** [comment] 2021-07-01 09:07
Hmmm... Now that I think of this, I'm not a mod author, but I've heard Optifabric has some compability issues. It's probably Optifabric's fault, even the guys over at Architectury API said so.

**Comment by Motschen** [comment] 2021-09-24 16:42
Duplicate of #16

**Closed as completed by Motschen** 2021-09-24 16:42 UTC
