### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by killuanter** [Motschen/Blur#116] opened 2024-12-25 08:40 UTC
on inventory or chest
![image_2024-12-25_153944793](https://github.com/user-attachments/assets/6e2410de-a361-40f7-a04e-c2285c72c919)
but it's working on menu
![image](https://github.com/user-attachments/assets/dbe417b4-8c65-4422-9500-f4583edbaaf5)
any way to fix this? thank you

note:
minecraft 1.21.1 neoforge ran with curseforge
mods:
![image](https://github.com/user-attachments/assets/91f5eb52-818a-421e-81e2-9b1e0a8d04ab)
![image](https://github.com/user-attachments/assets/910f118f-f4d8-4bb5-b16e-1f9fda2749bd)
![image](https://github.com/user-attachments/assets/b58a4b04-76ae-4b8a-8134-6562f4d1060b)

**Comment by Motschen** [comment] 2024-12-29 14:28
Duplicate of #110

**Closed as not planned by Motschen** 2024-12-29 14:28 UTC
