### ISSUE TITLE
Containers only blur during fade out

### ISSUE THREAD

**Issue by Jakobuo** [Motschen/Blur#114] opened 2024-11-21 23:46 UTC
Version:
Minecraft 1.21.1
NeoForge 21.1.80
Blur+ 5.0.0
MidnightLib 1.6.3

Issue:
When opening a container, there is no blur until it's closed again. At this point, blur suddenly starts and fades out as it should.

Expected behaviour:
The blur should fade in and remain as long as the container is opened before fading out.

Notes:
When blur in containers is disabled, there is no blur at all, as intended.
I haven't testing everything with an inventory.
Things I tested:
Chest, Barrel
Crafting Table
Crafter
Inventory
Edit: I forgot to mention that menus also work as intended.

**Comment by killuanter** [comment] 2024-12-25 08:44
have you found a way to solve this yet?

**Comment by Motschen** [comment] 2024-12-29 14:28
Duplicate of #110

**Closed as not planned by Motschen** 2024-12-29 14:28 UTC
